package com.example.presta.publicidadexample.dataAccess.model;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "GPS_DATA".
 */
public class GpsData {

    private Long id;
    private java.util.Date fecha;
    private Double lat;
    private Double lon;
    private String modo;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GpsData() {
    }

    public GpsData(Long id) {
        this.id = id;
    }

    public GpsData(Long id, java.util.Date fecha, Double lat, Double lon, String modo) {
        this.id = id;
        this.fecha = fecha;
        this.lat = lat;
        this.lon = lon;
        this.modo = modo;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getFecha() {
        return fecha;
    }

    public void setFecha(java.util.Date fecha) {
        this.fecha = fecha;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLon() {
        return lon;
    }

    public void setLon(Double lon) {
        this.lon = lon;
    }

    public String getModo() {
        return modo;
    }

    public void setModo(String modo) {
        this.modo = modo;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
