package com.example.presta.publicidadexample.dataAccess.model.v2;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "APP_CONFIG".
 */
public class AppConfig {

    private Long id;
    private Boolean esPrimerUso;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public AppConfig() {
    }

    public AppConfig(Long id) {
        this.id = id;
    }

    public AppConfig(Long id, Boolean esPrimerUso) {
        this.id = id;
        this.esPrimerUso = esPrimerUso;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getEsPrimerUso() {
        return esPrimerUso;
    }

    public void setEsPrimerUso(Boolean esPrimerUso) {
        this.esPrimerUso = esPrimerUso;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
