package com.example.presta.publicidadexample.dataAccess.model.v2;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "PHONE_DATA".
 */
public class PhoneData {

    private Long id;
    private String deviceId;
    private String subscriberId;
    private String simSerialNumber;
    private String line1Number;
    private String networkOperatorName;
    private String networkCountryIso;
    private Integer SDK_INT;
    private String MANUFACTURER;
    private String MODEL;
    private Boolean datosSincronizados;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public PhoneData() {
    }

    public PhoneData(Long id) {
        this.id = id;
    }

    public PhoneData(Long id, String deviceId, String subscriberId, String simSerialNumber, String line1Number, String networkOperatorName, String networkCountryIso, Integer SDK_INT, String MANUFACTURER, String MODEL, Boolean datosSincronizados) {
        this.id = id;
        this.deviceId = deviceId;
        this.subscriberId = subscriberId;
        this.simSerialNumber = simSerialNumber;
        this.line1Number = line1Number;
        this.networkOperatorName = networkOperatorName;
        this.networkCountryIso = networkCountryIso;
        this.SDK_INT = SDK_INT;
        this.MANUFACTURER = MANUFACTURER;
        this.MODEL = MODEL;
        this.datosSincronizados = datosSincronizados;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDeviceId() {
        return deviceId;
    }

    public void setDeviceId(String deviceId) {
        this.deviceId = deviceId;
    }

    public String getSubscriberId() {
        return subscriberId;
    }

    public void setSubscriberId(String subscriberId) {
        this.subscriberId = subscriberId;
    }

    public String getSimSerialNumber() {
        return simSerialNumber;
    }

    public void setSimSerialNumber(String simSerialNumber) {
        this.simSerialNumber = simSerialNumber;
    }

    public String getLine1Number() {
        return line1Number;
    }

    public void setLine1Number(String line1Number) {
        this.line1Number = line1Number;
    }

    public String getNetworkOperatorName() {
        return networkOperatorName;
    }

    public void setNetworkOperatorName(String networkOperatorName) {
        this.networkOperatorName = networkOperatorName;
    }

    public String getNetworkCountryIso() {
        return networkCountryIso;
    }

    public void setNetworkCountryIso(String networkCountryIso) {
        this.networkCountryIso = networkCountryIso;
    }

    public Integer getSDK_INT() {
        return SDK_INT;
    }

    public void setSDK_INT(Integer SDK_INT) {
        this.SDK_INT = SDK_INT;
    }

    public String getMANUFACTURER() {
        return MANUFACTURER;
    }

    public void setMANUFACTURER(String MANUFACTURER) {
        this.MANUFACTURER = MANUFACTURER;
    }

    public String getMODEL() {
        return MODEL;
    }

    public void setMODEL(String MODEL) {
        this.MODEL = MODEL;
    }

    public Boolean getDatosSincronizados() {
        return datosSincronizados;
    }

    public void setDatosSincronizados(Boolean datosSincronizados) {
        this.datosSincronizados = datosSincronizados;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
