package com.example.presta.publicidadexample.dataAccess.model.v2;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "USER_DATA".
 */
public class UserData {

    private Long id;
    private java.util.Date fechaNacimiento;
    private String sexo;
    private String cuentas;
    private Boolean datosSincronizados;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public UserData() {
    }

    public UserData(Long id) {
        this.id = id;
    }

    public UserData(Long id, java.util.Date fechaNacimiento, String sexo, String cuentas, Boolean datosSincronizados) {
        this.id = id;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
        this.cuentas = cuentas;
        this.datosSincronizados = datosSincronizados;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(java.util.Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public String getCuentas() {
        return cuentas;
    }

    public void setCuentas(String cuentas) {
        this.cuentas = cuentas;
    }

    public Boolean getDatosSincronizados() {
        return datosSincronizados;
    }

    public void setDatosSincronizados(Boolean datosSincronizados) {
        this.datosSincronizados = datosSincronizados;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
