package com.example.presta.publicidadexample.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "APP_CONFIG".
 */
public class AppConfig {

    private Long id;
    private Boolean esPrimerUso;

    public AppConfig() {
    }

    public AppConfig(Long id) {
        this.id = id;
    }

    public AppConfig(Long id, Boolean esPrimerUso) {
        this.id = id;
        this.esPrimerUso = esPrimerUso;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Boolean getEsPrimerUso() {
        return esPrimerUso;
    }

    public void setEsPrimerUso(Boolean esPrimerUso) {
        this.esPrimerUso = esPrimerUso;
    }

}
