package com.example.presta.publicidadexample.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "USER_DATA".
 */
public class UserData {

    private Long id;
    private java.util.Date fechaNacimiento;
    private String sexo;
    private Boolean datosSincronizados;

    public UserData() {
    }

    public UserData(Long id) {
        this.id = id;
    }

    public UserData(Long id, java.util.Date fechaNacimiento, String sexo, Boolean datosSincronizados) {
        this.id = id;
        this.fechaNacimiento = fechaNacimiento;
        this.sexo = sexo;
        this.datosSincronizados = datosSincronizados;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public java.util.Date getFechaNacimiento() {
        return fechaNacimiento;
    }

    public void setFechaNacimiento(java.util.Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    public String getSexo() {
        return sexo;
    }

    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    public Boolean getDatosSincronizados() {
        return datosSincronizados;
    }

    public void setDatosSincronizados(Boolean datosSincronizados) {
        this.datosSincronizados = datosSincronizados;
    }

}
